services:
  - type: web
    name: queroimprimir3d-api
    env: node
    rootDir: apps/backend
    buildCommand: rm -rf node_modules && npm install --include=dev && npm run build
    startCommand: node dist/main
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001
